version: '3.8'

services:
  jupyter-multilang:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - jupyter-data:/root/.jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''

volumes:
  jupyter-data:
